export const features = [
  {
    icon: 'ph:book-open',
    title: 'Bilingual Lessons',
    description:
      'Structured lessons with English ↔ word content, audio pronunciation, and visual aids.',
    color: 'text-blue-600 bg-blue-50/50',
  },
  {
    icon: 'mdi:brain',
    title: 'Spaced Repetition',
    description:
      'Smart flashcard system that adapts to your learning pace for optimal retention.',
    color: 'text-purple-600 bg-purple-50/50',
  },
  {
    icon: 'lucide:message-square',
    title: 'Interactive Dialogues',
    description:
      'Practice real conversations with branching dialogue trees and feedback.',
    color: 'text-green-600 bg-green-50/50',
  },
  {
    icon: 'mdi:dictionary',
    title: 'Built-in Dictionary',
    description:
      'Comprehensive EN ↔ DE dictionary with IPA, examples, and personal bookmarks.',
    color: 'text-orange-600 bg-orange-50/50',
  },
  {
    icon: 'mdi:progress-check',
    title: 'Level-Based Learning',
    description:
      'Structured progression from A1 to B2 with clear milestones and assessments.',
    color: 'text-red-600 bg-red-50/50',
  },
  {
    icon: 'mdi:trophy',
    title: 'Gamification',
    description:
      'Earn points, unlock achievements, and compete with friends on leaderboards.',
    color: 'text-yellow-600 bg-yellow-50/50',
  },
  {
    icon: 'mdi:note',
    title: 'Personal Notes',
    description:
      'Highlight difficult words, add personal notes, and create custom study sets.',
    color: 'text-indigo-600 bg-indigo-50/50',
  },
  {
    icon: 'mdi:lightbulb',
    title: 'Smart Roadmap',
    description:
      'AI-powered daily suggestions and personalized learning path recommendations.',
    color: 'text-pink-600 bg-pink-50/50',
  },
  {
    icon: 'mdi:globe',
    title: 'Topic-Based Learning',
    description:
      'Learn word for specific contexts: travel, business, interviews, and more.',
    color: 'text-teal-600 bg-teal-50/50',
  },
]
export const levels = [
  {
    code: 'A1',
    title: 'Beginner',
    description: 'Basic phrases and everyday expressions',
    textColor: 'text-green-700',
    features: [
      'Greetings & introductions',
      'Numbers & time',
      'Basic vocabulary',
    ],
  },
  {
    code: 'A2',
    title: 'Elementary',
    description: 'Simple conversations and familiar topics',
    textColor: 'text-blue-700',
    features: ['Past tense basics', 'Shopping & dining', 'Family & hobbies'],
  },
  {
    code: 'B1',
    title: 'Intermediate',
    description: 'Clear standard language on familiar matters',
    textColor: 'text-purple-700',
    features: ['Work & studies', 'Travel situations', 'Express opinions'],
  },
  {
    code: 'B2',
    title: 'Upper Intermediate',
    description: 'Complex texts and abstract topics',
    textColor: 'text-orange-700',
    features: ['Professional word', 'Complex grammar', 'Fluent discussions'],
  },
]

export const sampleLesson = {
  title: 'At the Restaurant',
  level: 'A2',
  vocabulary: [
    {
      id: '1',
      word: 'Die Speisekarte',
      meaning: 'Menu',
      example: 'Könnte ich bitte die Speisekarte haben?',
      level: 'A2',
      audioUrl: '',
      imageUrl: undefined,
      transcription: '/ˈʃpaɪzəˌkartə/',
      type: 'noun',
    },
    {
      id: '2',
      word: 'Der Kellner',
      meaning: 'Waiter',
      example: 'Der Kellner bringt die Rechnung.',
      level: 'A2',
      audioUrl: '',
      imageUrl: undefined,
      transcription: '/ˈkɛlnɐ/',
      type: 'noun',
    },
    {
      id: '3',
      word: 'Die Rechnung',
      meaning: 'Bill',
      example: 'Ich möchte die Rechnung bezahlen.',
      level: 'A2',
      audioUrl: '',
      imageUrl: undefined,
      transcription: '/ˈrɛçnʊŋ/',
      type: 'noun',
    },
  ],
  sentences: [
    {
      id: '1',
      meaning: 'Could I have the menu, please?',
      word: 'Könnte ich bitte die Speisekarte haben?',
      level: 'A2',
      audioUrl: '',
      type: 'sentence',
    },
    {
      id: '2',
      meaning: 'I would like to order.',
      word: 'Ich möchte gerne bestellen.',
      level: 'A2',
      audioUrl: '',
      type: 'sentence',
    },
  ],
}

export const topicsData = {
  A1: [
    {
      id: 'e316b2f9-b5c6-4s58-9816-f30c2ea6967d',
      title: 'Travel & Transportation',
      description: 'Essential vocabulary for traveling in Germany',
      paragraph: `Ich fahre gerne mit dem Zug durch Deutschland. Der Bahnhof ist sehr groß und modern. Mein Ticket kostet zwanzig Euro. Die Reise dauert drei Stunden. Ich nehme auch manchmal das Flugzeug, aber das ist teurer. Am Flughafen muss ich meinen Pass zeigen. Die Flugreise ist schneller, aber ich mag die Landschaft vom Zug aus sehen.`,
      difficulty: 'Beginner',
      englishTranslation:
        'I like to travel by train through Germany. The train station is very big and modern. My ticket costs twenty euros. The journey takes three hours. I also take the plane sometimes, but that is more expensive. I have to show my passport at the airport. The flight journey is faster, but I like to see the landscape from the train.',
      estimatedTime: '15 min',
      wordsCount: 28,
      completedWords: 12,
      masteredWords: 8,
    },
    {
      id: 'e316b2f9-b5c6-4d58-9816-f3gegedea6967d',
      title: 'At the Restaurant',
      description: 'Learn how to order food and interact with waiters',
      paragraph: `Guten Abend! Ich hätte gerne einen Tisch für zwei Personen. Haben Sie die Speisekarte auf Englisch? Ich möchte das Schnitzel mit Kartoffeln bestellen. Meine Freundin nimmt den Salat. Können wir auch eine Flasche Wasser haben? Das Essen schmeckt sehr gut. Die Rechnung, bitte! Ist Trinkgeld üblich in Deutschland?`,
      difficulty: 'Beginner',
      englishTranslation:
        'Good evening! I would like a table for two. Do you have the menu in English? I would like to order the schnitzel with potatoes. My friend will have the salad. Can we also have a bottle of water? The food tastes very good. The bill, please! Is tipping customary in Germany?',
      estimatedTime: '18 min',
      wordsCount: 32,
      completedWords: 5,
      masteredWords: 3,
    },
    {
      id: 'e32f6h2f9-b5c6-4d58-9816-321b2f9hj0c6',
      title: 'Shopping',
      description: 'Learn how to shop in Germany',
      paragraph: `Hallo! Ich möchte ein Hemd und eine Hose kaufen. Haben Sie eine Größe 42? Ich möchte auch eine Jacke. Kann ich sie anprobieren? Die Jacke ist zu klein. Ich möchte eine andere Größe. Die Hose ist zu lang. Ich möchte eine kürzere Hose. Danke!`,
      difficulty: 'Beginner',
      englishTranslation: `Hello! I would like to buy a shirt and a pair of pants. Do you have a size 42? I would also like a jacket. Can I try it on? The jacket is too small. I would like a different size. The pants are too long. I would like a shorter pair of pants. Thank you!`,
      estimatedTime: '15 min',
      wordsCount: 25,
      completedWords: 8,
      masteredWords: 5,
    },
    {
      id: 'e32f6h2f9-b5c6-4d58-9816-xyzabc123456',
      title: 'Daily Routines',
      description: 'Vocabulary for daily activities and routines',
      paragraph: `Ich stehe jeden Morgen um sieben Uhr auf. Nach dem Frühstück gehe ich zur Arbeit. Am Abend koche ich oft das Abendessen. Nach dem Essen sehe ich fern oder lese ein Buch. Um zehn Uhr gehe ich schlafen.`,
      difficulty: 'Beginner',
      englishTranslation:
        'I get up every morning at seven o’clock. After breakfast, I go to work. In the evening, I often cook dinner. After eating, I watch TV or read a book. At ten o’clock, I go to sleep.',
      estimatedTime: '15 min',
      wordsCount: 40,
      completedWords: 6,
      masteredWords: 4,
    },
    {
      id: 'e32f6h2f9-b5c6-4d58-9816-ijklmnop123456',
      title: 'Weather & Seasons',
      description: 'Talking about weather and seasons in Germany',
      paragraph: `Heute ist es sonnig und warm. Im Sommer gehen viele Menschen schwimmen. Im Winter gibt es oft Schnee. Ich liebe den Herbst, wenn die Blätter bunt werden. Das Wetter kann sehr wechselhaft sein.`,
      difficulty: 'Beginner',
      englishTranslation:
        'Today it is sunny and warm. In summer, many people go swimming. In winter, there is often snow. I love autumn when the leaves turn colorful. The weather can be very changeable.',
      estimatedTime: '15 min',
      wordsCount: 35,
      completedWords: 7,
      masteredWords: 3,
    },
    {
      id: 'e32f6h2f9-b5c6-4d58-9816-mnopqrst123456',
      title: 'Hobbies & Free Time',
      description: 'Discussing hobbies and leisure activities',
      paragraph: `In meiner Freizeit spiele ich gerne Fußball und gehe ins Kino. Ich lese auch Bücher und mache Spaziergänge im Park. Meine Freunde und ich treffen uns oft am Wochenende. Wir spielen Spiele oder gehen essen.`,
      difficulty: 'Beginner',
      englishTranslation:
        'In my free time, I like to play football and go to the cinema. I also read books and take walks in the park. My friends and I often meet on weekends. We play games or go out to eat.',
      estimatedTime: '15 min',
      wordsCount: 40,
      completedWords: 5,
      masteredWords: 2,
    },
  ],
  A2: [
    {
      id: 'e321b2f9-b5c6-4d58-9816-sdfs2ea6967d',
      title: 'Work & Office Life',
      description: 'Professional German vocabulary and office situations',
      paragraph: `Mein Arbeitsplatz befindet sich im Stadtzentrum. Ich arbeite in einem modernen Bürogebäude. Meine Kollegen sind sehr freundlich und hilfsbereit. Wir haben täglich um neun Uhr eine Besprechung. Mein Chef ist streng, aber fair. Die Mittagspause dauert eine Stunde. Nach Feierabend gehe ich oft mit den Kollegen etwas trinken.`,
      difficulty: 'Elementary',
      englishTranslation:
        "My workplace is located in the city center. I work in a modern office building. My colleagues are very friendly and helpful. We have a meeting every day at nine o'clock. My boss is strict but fair. The lunch break lasts one hour. After work, I often go for a drink with my colleagues.",
      estimatedTime: '20 min',
      wordsCount: 35,
      completedWords: 8,
      masteredWords: 2,
    },
    {
      id: 'e321b2f9-b5c6-4d58-9816-abcdef123456',
      title: 'Health & Fitness',
      description: 'Vocabulary related to health and fitness activities',
      paragraph: `Ich gehe dreimal pro Woche ins Fitnessstudio. Es ist wichtig, fit zu bleiben. Ich liebe es, Yoga zu machen und zu joggen. Gesundes Essen ist ebenfalls wichtig. Ich esse viel Obst und Gemüse. Manchmal gehe ich auch schwimmen. Sport hilft mir, Stress abzubauen.`,
      difficulty: 'Elementary',
      englishTranslation:
        'I go to the gym three times a week. It is important to stay fit. I love to do yoga and jog. Healthy food is also important. I eat a lot of fruits and vegetables. Sometimes I also go swimming. Sports help me reduce stress.',
      estimatedTime: '20 min',
      wordsCount: 40,
      completedWords: 5,
      masteredWords: 3,
    },
    {
      id: 'e321b2f9-b5c6-4d58-9816-ghijklm123456',
      title: 'Home & Family',
      description: 'Discussing home and family topics',
      paragraph: `Ich wohne mit meiner Familie in einer Wohnung. Wir haben ein Wohnzimmer, eine Küche und zwei Schlafzimmer. Mein Bruder ist ein Student und meine Schwester arbeitet. Am Wochenende verbringen wir viel Zeit zusammen. Wir gehen oft ins Kino oder machen einen Ausflug.`,
      difficulty: 'Elementary',
      englishTranslation:
        'I live with my family in an apartment. We have a living room, a kitchen, and two bedrooms. My brother is a student and my sister works. On weekends, we spend a lot of time together. We often go to the cinema or take a trip.',
      estimatedTime: '20 min',
      wordsCount: 35,
      completedWords: 6,
      masteredWords: 4,
    },
    {
      id: 'e321b2f9-b5c6-4d58-9816-pqrst123456',
      title: 'Celebrations & Holidays',
      description: 'Learn vocabulary related to celebrations and holidays',
      paragraph: `Wir feiern Weihnachten und Neujahr mit der Familie. An meinem Geburtstag lade ich Freunde ein. Es gibt Kuchen und Geschenke. Ostern ist auch eine schöne Zeit, in der wir Eier färben und Ostereier suchen.`,
      difficulty: 'Elementary',
      englishTranslation:
        'We celebrate Christmas and New Year with the family. On my birthday, I invite friends. There is cake and gifts. Easter is also a lovely time when we dye eggs and hunt for Easter eggs.',
      estimatedTime: '20 min',
      wordsCount: 40,
      completedWords: 5,
      masteredWords: 2,
    },
    {
      id: 'e321b2f9-b5c6-4d58-9816-uvwxyz123456',
      title: 'Travel Experiences',
      description: 'Discussing travel experiences and destinations',
      paragraph: `Ich habe viele Länder besucht. Letztes Jahr bin ich nach Spanien gereist. Die Strände waren wunderschön. In Frankreich habe ich das Essen sehr genossen. Reisen erweitert den Horizont und bringt viele neue Erfahrungen.`,
      difficulty: 'Elementary',
      englishTranslation:
        'I have visited many countries. Last year, I traveled to Spain. The beaches were beautiful. In France, I really enjoyed the food. Traveling broadens the horizon and brings many new experiences.',
      estimatedTime: '20 min',
      wordsCount: 45,
      completedWords: 6,
      masteredWords: 3,
    },
  ],
  B1: [
    {
      id: 'e321b2f9-54hg-dfs6-9816-sdfs2ea6967d',
      title: 'German Culture & Traditions',
      description: 'Explore German customs, festivals, and cultural practices',
      paragraph: `Die deutsche Kultur ist sehr vielfältig und reich an Traditionen. Das Oktoberfest in München ist weltberühmt und zieht Millionen von Besuchern an. Deutsche feiern auch gerne Weihnachtsmärkte im Winter, wo man Glühwein trinkt und handgemachte Geschenke kauft. Die Deutschen sind bekannt für ihre Pünktlichkeit und Ordnung. Sonntags bleiben die meisten Geschäfte geschlossen, weil es ein Ruhetag ist.`,
      difficulty: 'Intermediate',
      englishTranslation:
        'German culture is very diverse and rich in traditions. The Oktoberfest in Munich is world-famous and attracts millions of visitors. Germans also enjoy Christmas markets in winter, where one drinks mulled wine and buys handmade gifts. Germans are known for their punctuality and order. On Sundays, most shops remain closed because it is a day of rest.',
      estimatedTime: '25 min',
      wordsCount: 42,
      completedWords: 3,
      masteredWords: 1,
    },
    {
      id: 'e321b2f9-54hg-dfs6-9816-opqrst123456',
      title: 'Education & Learning',
      description: 'Discussing education systems and learning methods',
      paragraph: `Das deutsche Bildungssystem ist sehr strukturiert. Kinder gehen zuerst in den Kindergarten und dann in die Grundschule. Nach der Grundschule können sie verschiedene weiterführende Schulen besuchen. Bildung ist in Deutschland sehr wichtig und viele Menschen lernen ihr Leben lang.`,
      difficulty: 'Intermediate',
      englishTranslation:
        'The German education system is very structured. Children first go to kindergarten and then to primary school. After primary school, they can attend different secondary schools. Education is very important in Germany, and many people learn throughout their lives.',
      estimatedTime: '30 min',
      wordsCount: 45,
      completedWords: 5,
      masteredWords: 2,
    },
    {
      id: 'e321b2f9-54hg-dfs6-9816-uvwxyz123456',
      title: 'Technology & Innovation',
      description: 'Exploring technology and its impact on society',
      paragraph: `Die Technologie verändert unser Leben ständig. Smartphones und das Internet sind aus unserem Alltag nicht mehr wegzudenken. In Deutschland gibt es viele Start-ups, die innovative Lösungen entwickeln. Künstliche Intelligenz ist ein wachsendes Feld und wird die Zukunft prägen.`,
      difficulty: 'Intermediate',
      englishTranslation:
        'Technology is constantly changing our lives. Smartphones and the internet are indispensable in our daily lives. In Germany, there are many start-ups developing innovative solutions. Artificial intelligence is a growing field and will shape the future.',
      estimatedTime: '30 min',
      wordsCount: 48,
      completedWords: 4,
      masteredWords: 1,
    },
    {
      id: 'e321b2f9-54hg-dfs6-9816-abcdefg123456',
      title: 'Food & Cooking',
      description: 'Discussing food preferences and cooking methods',
      paragraph: `Ich koche gerne. Deutsche Küche ist sehr vielfältig. Ich liebe es, Sauerkraut und Bratwurst zuzubereiten. Bei Familientreffen bringen alle etwas zu essen mit. Kochen ist für mich eine entspannende Tätigkeit.`,
      difficulty: 'Intermediate',
      englishTranslation:
        'I enjoy cooking. German cuisine is very diverse. I love preparing sauerkraut and bratwurst. At family gatherings, everyone brings something to eat. Cooking is a relaxing activity for me.',
      estimatedTime: '30 min',
      wordsCount: 45,
      completedWords: 5,
      masteredWords: 3,
    },
    {
      id: 'e321b2f9-54hg-dfs6-9816-hijklmnop123456',
      title: 'Sports & Recreation',
      description: 'Talking about sports and recreational activities',
      paragraph: `Sport ist wichtig für die Gesundheit. Ich spiele Fußball und gehe oft schwimmen. In Deutschland sind viele Sportarten beliebt, wie Handball und Basketball. Auch Radfahren ist sehr verbreitet.`,
      difficulty: 'Intermediate',
      englishTranslation:
        'Sports are important for health. I play football and often go swimming. Many sports are popular in Germany, such as handball and basketball. Cycling is also very common.',
      estimatedTime: '30 min',
      wordsCount: 42,
      completedWords: 4,
      masteredWords: 2,
    },
  ],
  B2: [
    {
      id: 'fdsf-b2f9-54hg-dfs6-9816-sdfs2ea6967d',
      title: 'Financial Transactions',
      description:
        'Learn about common financial transactions and their translations',
      paragraph: `In Deutschland gibt es viele Möglichkeiten, Finanztransaktionen durchzuführen. Sie können Geld am Geldautomaten abheben oder in einer Bankfiliale ein Konto eröffnen. Es ist wichtig, die verschiedenen Arten von Konten und ihre Gebühren zu verstehen. Kreditkarten sind weit verbreitet, und viele Geschäfte akzeptieren sie. Auch Online-Banking wird immer beliebter.`,
      difficulty: 'Upper Intermediate',
      englishTranslation:
        'In Germany, there are many ways to conduct financial transactions. You can withdraw money at an ATM or open an account at a bank branch. It is important to understand the different types of accounts and their fees. Credit cards are widely used, and many shops accept them. Online banking is also becoming increasingly popular.',
      estimatedTime: '30 min',
      wordsCount: 50,
      completedWords: 0,
      masteredWords: 0,
    },
    {
      id: 'fdsf-b2f9-54hg-dfs6-9816-abcdefg123456',
      title: 'Environmental Issues',
      description: 'Discussing environmental challenges and solutions',
      paragraph: `Umweltprobleme sind weltweit ein großes Thema. In Deutschland wird viel für den Klimaschutz getan. Erneuerbare Energien wie Wind- und Solarenergie gewinnen an Bedeutung. Jeder kann einen Beitrag leisten, indem er umweltbewusst handelt und Ressourcen schont.`,
      difficulty: 'Upper Intermediate',
      englishTranslation:
        'Environmental issues are a major topic worldwide. In Germany, a lot is being done for climate protection. Renewable energies like wind and solar energy are gaining importance. Everyone can contribute by acting environmentally conscious and conserving resources.',
      estimatedTime: '35 min',
      wordsCount: 45,
      completedWords: 0,
      masteredWords: 0,
    },
    {
      id: 'fdsf-b2f9-54hg-dfs6-9816-hijklmnop123456',
      title: 'Politics & Society',
      description: 'Understanding political structures and societal issues',
      paragraph: `Die Politik in Deutschland ist demokratisch organisiert. Es gibt verschiedene Parteien, die um die Stimmen der Bürger kämpfen. Soziale Themen wie Migration und Bildung stehen häufig im Vordergrund der politischen Diskussion. Die Bürger sind aktiv und nehmen an Wahlen teil.`,
      difficulty: 'Upper Intermediate',
      englishTranslation:
        'Politics in Germany is organized democratically. There are different parties competing for the votes of the citizens. Social issues like migration and education are often at the forefront of political discussion. Citizens are active and participate in elections.',
      estimatedTime: '35 min',
      wordsCount: 50,
      completedWords: 0,
      masteredWords: 0,
    },
    {
      id: 'fdsf-b2f9-54hg-dfs6-9816-qrstuv123456',
      title: 'Media & Communication',
      description: 'Discussing the role of media and communication in society',
      paragraph: `Die Medien haben einen großen Einfluss auf die Gesellschaft. Nachrichten werden schnell verbreitet, und soziale Medien sind allgegenwärtig. In Deutschland gibt es viele Zeitungen und Fernsehsender. Medienkompetenz ist wichtig, um Informationen kritisch zu bewerten.`,
      difficulty: 'Upper Intermediate',
      englishTranslation:
        'The media have a great influence on society. News spreads quickly, and social media is everywhere. In Germany, there are many newspapers and television channels. Media literacy is important to critically evaluate information.',
      estimatedTime: '35 min',
      wordsCount: 50,
      completedWords: 0,
      masteredWords: 0,
    },
    {
      id: 'fdsf-b2f9-54hg-dfs6-9816-wxyz123456',
      title: 'Cultural Exchange',
      description: 'Exploring cultural exchange and its benefits',
      paragraph: `Kultureller Austausch bringt Menschen zusammen. In Deutschland gibt es viele Programme für Austauschschüler. Diese Programme fördern das Verständnis zwischen verschiedenen Kulturen. Reisen und das Kennenlernen neuer Traditionen bereichern unser Leben.`,
      difficulty: 'Upper Intermediate',
      englishTranslation:
        'Cultural exchange brings people together. In Germany, there are many programs for exchange students. These programs promote understanding between different cultures. Traveling and getting to know new traditions enrich our lives.',
      estimatedTime: '35 min',
      wordsCount: 45,
      completedWords: 0,
      masteredWords: 0,
    },
  ],
  C1: [
    {
      id: '34321-b2f9-54hg-dfs6-9816-sdcs2eacc67d',
      title: 'Business Communication',
      description:
        'Advanced vocabulary and expressions for professional settings',
      paragraph: `Die Geschäftswelt erfordert präzise Kommunikation. Meetings müssen gut vorbereitet werden, und die Teilnehmer sollten ihre Standpunkte klar und überzeugend darlegen. Das Verständnis von Fachbegriffen ist entscheidend, um effektiv an Diskussionen teilzunehmen. Networking und der Aufbau von Beziehungen sind ebenfalls wichtige Aspekte im Berufsleben.`,
      difficulty: 'Advanced',
      englishTranslation:
        'The business world requires precise communication. Meetings must be well-prepared, and participants should present their points clearly and convincingly. Understanding technical terms is essential for effectively participating in discussions. Networking and building relationships are also important aspects of professional life.',
      estimatedTime: '35 min',
      wordsCount: 60,
      completedWords: 0,
      masteredWords: 0,
    },
    {
      id: '34321-b2f9-54hg-dfs6-9816-qrstuvwxyz123456',
      title: 'Philosophy & Ethics',
      description: 'Exploring philosophical concepts and ethical dilemmas',
      paragraph: `Philosophie beschäftigt sich mit grundlegenden Fragen des Lebens und der Moral. Ethik untersucht, was richtig und falsch ist. In Deutschland gibt es viele Denker, die wichtige Beiträge zu diesen Themen geleistet haben. Diskussionen über Ethik sind oft komplex und vielschichtig.`,
      difficulty: 'Advanced',
      englishTranslation:
        'Philosophy deals with fundamental questions of life and morality. Ethics examines what is right and wrong. In Germany, there are many thinkers who have made important contributions to these topics. Discussions about ethics are often complex and multifaceted.',
      estimatedTime: '40 min',
      wordsCount: 65,
      completedWords: 0,
      masteredWords: 0,
    },
    {
      id: '34321-b2f9-54hg-dfs6-9816-abcdefg123456',
      title: 'Global Issues',
      description: 'Discussing global challenges and international relations',
      paragraph: `Globale Herausforderungen wie Klimawandel und Migration erfordern internationale Zusammenarbeit. Deutschland spielt eine wichtige Rolle in der Europäischen Union. Die Politik muss Lösungen finden, die für alle Länder akzeptabel sind. Dialog und Diplomatie sind entscheidend für den Frieden.`,
      difficulty: 'Advanced',
      englishTranslation:
        'Global challenges like climate change and migration require international cooperation. Germany plays an important role in the European Union. Politics must find solutions that are acceptable to all countries. Dialogue and diplomacy are crucial for peace.',
      estimatedTime: '40 min',
      wordsCount: 60,
      completedWords: 0,
      masteredWords: 0,
    },
    {
      id: '34321-b2f9-54hg-dfs6-9816-hijklmnop123456',
      title: 'Sustainability & Environment',
      description:
        'Discussing sustainable practices and environmental protection',
      paragraph: `Nachhaltigkeit ist ein wichtiges Thema in der modernen Gesellschaft. In Deutschland gibt es viele Initiativen für Umweltschutz. Die Menschen sind sich der Bedeutung von Recycling und erneuerbaren Energien bewusst. Jeder kann einen Beitrag zur Erhaltung unseres Planeten leisten.`,
      difficulty: 'Advanced',
      englishTranslation:
        'Sustainability is an important topic in modern society. In Germany, there are many initiatives for environmental protection. People are aware of the importance of recycling and renewable energies. Everyone can contribute to preserving our planet.',
      estimatedTime: '40 min',
      wordsCount: 70,
      completedWords: 0,
      masteredWords: 0,
    },
    {
      id: '34321-b2f9-54hg-dfs6-9816-qrstuvwxyz123456',
      title: 'Art & Literature',
      description: 'Exploring the impact of art and literature on society',
      paragraph: `Kunst und Literatur reflektieren oft die Gesellschaft. In Deutschland gibt es viele bedeutende Künstler und Schriftsteller. Ihre Werke bieten Einblicke in verschiedene Lebensweisen und Denkweisen. Kunst kann Menschen inspirieren und zum Nachdenken anregen.`,
      difficulty: 'Advanced',
      englishTranslation:
        'Art and literature often reflect society. In Germany, there are many significant artists and writers. Their works provide insights into different ways of life and ways of thinking. Art can inspire people and provoke thought.',
      estimatedTime: '40 min',
      wordsCount: 65,
      completedWords: 0,
      masteredWords: 0,
    },
  ],
  C2: [
    {
      id: '43hg-dfs6-9816-sdfs2ea6967d',
      title: 'Cultural Nuances',
      description:
        'Understanding subtle differences in cultural references and idioms',
      paragraph: `Die deutsche Sprache enthält viele Redewendungen, die oft nicht wörtlich übersetzt werden können. Ein tiefes Verständnis der Kultur ist notwendig, um diese Nuancen zu erfassen. Beispielsweise sagt man "Tomaten auf den Augen haben", was bedeutet, dass jemand etwas Offensichtliches nicht sieht. Solche Ausdrücke sind Teil der Alltagskommunikation und zeigen die Vielfalt der Sprache.`,
      difficulty: 'Proficient',
      englishTranslation:
        'The German language contains many idioms that often cannot be translated literally. A deep understanding of the culture is necessary to grasp these nuances. For example, one says "to have tomatoes on the eyes," which means that someone does not see something obvious. Such expressions are part of everyday communication and demonstrate the diversity of the language.',
      estimatedTime: '40 min',
      wordsCount: 70,
      completedWords: 0,
      masteredWords: 0,
    },
    {
      id: '43hg-dfs6-9816-sdfs2ea6967d2',
      title: 'Literature & Art',
      description:
        'Exploring German literature, art movements, and their impact',
      paragraph: `Die deutsche Literatur hat viele berühmte Schriftsteller hervorgebracht, wie Goethe und Schiller. Kunstbewegungen wie der Expressionismus haben die Welt der Kunst beeinflusst. In Museen kann man viele bedeutende Werke bewundern. Kunst und Literatur sind Spiegel der Gesellschaft.`,
      difficulty: 'Proficient',
      englishTranslation:
        'German literature has produced many famous writers, such as Goethe and Schiller. Art movements like Expressionism have influenced the art world. In museums, one can admire many significant works. Art and literature are mirrors of society.',
      estimatedTime: '45 min',
      wordsCount: 65,
      completedWords: 0,
      masteredWords: 0,
    },
    {
      id: '43hg-dfs6-9816-sdfs2ea6967d3',
      title: 'Advanced Academic Discourse',
      description: 'Engaging in complex academic discussions and debates',
      paragraph: `Akademische Diskurse erfordern ein tiefes Verständnis des Themas. Argumentation und kritisches Denken sind unerlässlich. In Deutschland gibt es viele Universitäten, die hervorragende Bildungsangebote anbieten. Studierende sind oft in Forschungsprojekte involviert und diskutieren aktuelle Themen.`,
      difficulty: 'Proficient',
      englishTranslation:
        'Academic discourse requires a deep understanding of the topic. Argumentation and critical thinking are essential. In Germany, there are many universities offering excellent educational programs. Students are often involved in research projects and discuss current topics.',
      estimatedTime: '45 min',
      wordsCount: 70,
      completedWords: 0,
      masteredWords: 0,
    },
    {
      id: '43hg-dfs6-9816-sdfs2ea6967d4',
      title: 'Philosophical Reflections',
      description: 'Delving into deep philosophical questions and reflections',
      paragraph: `Philosophische Überlegungen sind oft komplex und erfordern tiefes Nachdenken. Themen wie Identität, Freiheit und das Wesen des Lebens sind zentral. In Deutschland gibt es viele Philosophen, die das Denken über diese Fragen geprägt haben.`,
      difficulty: 'Proficient',
      englishTranslation:
        'Philosophical reflections are often complex and require deep thinking. Topics like identity, freedom, and the nature of life are central. In Germany, there are many philosophers who have shaped thinking about these questions.',
      estimatedTime: '45 min',
      wordsCount: 65,
      completedWords: 0,
      masteredWords: 0,
    },
    {
      id: '43hg-dfs6-9816-sdfs2ea6967d5',
      title: 'Ethics in Modern Society',
      description:
        'Exploring ethical dilemmas and their implications in contemporary contexts',
      paragraph: `Ethische Dilemmata sind in der modernen Gesellschaft allgegenwärtig. Themen wie Datenschutz, Bioethik und soziale Gerechtigkeit stehen im Fokus. Die Fähigkeit, ethische Entscheidungen zu treffen, ist entscheidend für das Zusammenleben in einer komplexen Welt.`,
      difficulty: 'Proficient',
      englishTranslation:
        'Ethical dilemmas are ever-present in modern society. Topics like data privacy, bioethics, and social justice are in focus. The ability to make ethical decisions is crucial for living together in a complex world.',
      estimatedTime: '45 min',
      wordsCount: 70,
      completedWords: 0,
      masteredWords: 0,
    },
  ],
}

export const demoFlashcards: VocabularyWord[] = [
  {
    id: 'fahre',
    word: 'fahre',
    meaning: 'drive/travel',
    transcription: '/ˈfaːrə/',
    difficulty: 'easy',
    topics: ['transportation'],
    synonyms: [],
    antonyms: [],
  },
  {
    id: 'bahnhof',
    word: 'der Bahnhof',
    meaning: 'train station',
    transcription: '/ˈbaːnhoːf/',
    difficulty: 'medium',
    topics: ['transportation'],
    synonyms: [],
    antonyms: [],
  },
  {
    id: 'ticket',
    word: 'das Ticket',
    meaning: 'ticket',
    transcription: '/ˈtɪkət/',
    difficulty: 'easy',
    topics: ['transportation'],
    synonyms: [],
    antonyms: [],
  },
  {
    id: 'reise',
    word: 'die Reise',
    meaning: 'journey/trip',
    transcription: '/ˈraɪzə/',
    difficulty: 'medium',
    topics: ['transportation'],
    synonyms: [],
    antonyms: [],
  },
  {
    id: 'flugzeug',
    word: 'das Flugzeug',
    meaning: 'airplane',
    transcription: '/ˈfluːktsɔɪk/',
    difficulty: 'medium',
    topics: ['transportation'],
    synonyms: [],
    antonyms: [],
  },
]
